# Generated by Django 4.0.4 on 2022-06-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMSAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='db_User',
        ),
    ]
