# Generated by Django 4.0.4 on 2022-06-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSAdmin', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('codeC', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('NameC', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'db_Client',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('codeS', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descriptionS', models.TextField(max_length=1000, null=True)),
                ('QteS', models.IntegerField()),
                ('prixS', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'db_Service',
            },
        ),
    ]
