# Generated by Django 4.0.4 on 2022-06-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMSAdmin', '0003_client_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operationID', models.AutoField(primary_key=True, serialize=False)),
                ('dateO', models.DateField()),
                ('timeO', models.TimeField()),
                ('adresseO', models.CharField(max_length=30)),
                ('destinationO', models.CharField(max_length=30)),
                ('distanceO', models.IntegerField(null=True)),
                ('clientO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMSAdmin.client')),
            ],
            options={
                'db_table': 'db_Operation',
            },
        ),
    ]
