# Generated by Django 4.0.4 on 2022-06-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMSAdmin', '0004_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='prixS',
            new_name='priceS',
        ),
        migrations.AddField(
            model_name='operation',
            name='total_costO',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='OperationInput',
            fields=[
                ('operation_inputID', models.AutoField(primary_key=True, serialize=False)),
                ('QteOI', models.IntegerField()),
                ('priceOI', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_priceOI', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('operationOI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMSAdmin.operation')),
                ('serviceOI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMSAdmin.service')),
            ],
            options={
                'db_table': 'db_OperationInput',
            },
        ),
    ]
