# Generated by Django 4.0.4 on 2022-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSAdmin', '0005_rename_prixs_service_prices_operation_total_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='unitS',
            field=models.CharField(default='Km', max_length=5),
        ),
    ]
