# Generated by Django 4.0.4 on 2022-06-27 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSAdmin', '0006_service_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='NameC',
            new_name='nameC',
        ),
        migrations.AddField(
            model_name='operation',
            name='isCanceledO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='isCompleteO',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operation',
            name='dateO',
            field=models.DateField(default=datetime.date(2022, 6, 27)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='timeO',
            field=models.TimeField(default=datetime.time(2, 36, 42, 496656)),
        ),
        migrations.AlterField(
            model_name='service',
            name='unitS',
            field=models.CharField(default='', max_length=5),
        ),
    ]
