# Generated by Django 4.0.4 on 2022-06-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSAdmin', '0007_rename_namec_client_namec_operation_iscanceledo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='distanceO',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='timeO',
            field=models.TimeField(null=True),
        ),
    ]
