# Generated by Django 4.0.5 on 2022-06-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSAdmin', '0009_alter_operation_timeo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='dateO',
        ),
        migrations.AddField(
            model_name='operation',
            name='dayO',
            field=models.IntegerField(default=29),
        ),
        migrations.AddField(
            model_name='operation',
            name='monthO',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='operation',
            name='yearO',
            field=models.IntegerField(default=2022),
        ),
    ]
